### PR TITLE
Add KMS to GC tool

### LINKED ISSUE #11432: [Bug]: Nessie GC: ClassNotFoundException: ... kms.model.EncryptionAlgorithmSpec
### What happened

Nessie GC on S3 compatible storage is failing in version `0.105.1`, but works in `0.105.0`.

```
INFO  org.apache.iceberg.CatalogUtil - Loading custom FileIO implementation: org.apache.iceberg.aws.s3.S3FileIO
Exception in thread "main" java.lang.NoClassDefFoundError
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
        at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:542)
        at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:567)
        at java.base/java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:653)
        at java.base/java.util.concurrent.ForkJoinPool.invoke(ForkJoinPool.java:2822)
        at org.projectnessie.gc.expire.local.DefaultLocalExpire.expire(DefaultLocalExpire.java:75)
        at org.projectnessie.gc.tool.cli.commands.BaseRepositoryCommand.expire(BaseRepositoryCommand.java:250)
        at org.projectnessie.gc.tool.cli.commands.MarkAndSweep.call(MarkAndSweep.java:57)
        at org.projectnessie.gc.tool.cli.commands.BaseRepositoryCommand.call(BaseRepositoryCommand.java:84)
        at org.projectnessie.gc.tool.cli.commands.BaseCommand.call(BaseCommand.java:26)
        at org.projectnessie.gc.tool.cli.commands.BaseCommand.call(BaseCommand.java:21)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2045)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
        at picocli.CommandLine.execute(CommandLine.java:2174)
        at org.projectnessie.gc.tool.cli.CLI.runMain(CLI.java:104)
        at org.projectnessie.gc.tool.cli.CLI.runMain(CLI.java:75)
        at org.projectnessie.gc.tool.cli.CLI.main(CLI.java:70)
Caused by: java.lang.NoClassDefFoundError: software/amazon/awssdk/services/kms/model/EncryptionAlgorithmSpec
        at org.apache.iceberg.aws.AwsProperties.<clinit>(AwsProperties.java:214)
        at org.apache.iceberg.aws.AwsClientFactories$DefaultAwsClientFactory.<init>(AwsClientFactories.java:100)
        at org.apache.iceberg.aws.AwsClientFactories.<clinit>(AwsClientFactories.java:49)
        at org.apache.iceberg.aws.S3FileIOAwsClientFactories.initialize(S3FileIOAwsClientFactories.java:45)
        at org.apache.iceberg.aws.s3.S3FileIO.initialize(S3FileIO.java:495)
        at org.apache.iceberg.CatalogUtil.loadFileIO(CatalogUtil.java:408)
        at org.apache.iceberg.io.ResolvingFileIO.lambda$io$1(ResolvingFileIO.java:198)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
        at org.apache.iceberg.io.ResolvingFileIO.io(ResolvingFileIO.java:187)
        at org.apache.iceberg.io.ResolvingFileIO.newInputFile(ResolvingFileIO.java:90)
        at org.apache.iceberg.TableMetadataParser.read(TableMetadataParser.java:294)
        at org.projectnessie.gc.iceberg.IcebergContentToFiles.extractTableFiles(IcebergContentToFiles.java:129)
        at org.projectnessie.gc.iceberg.IcebergContentToFiles.extractFiles(IcebergContentToFiles.java:98)
        at org.projectnessie.gc.expire.PerContentDeleteExpired.lambda$identifyLiveFiles$2(PerContentDeleteExpired.java:128)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
        at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1715)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.ReduceOps$5.evaluateSequential(ReduceOps.java:258)
        at java.base/java.util.stream.ReduceOps$5.evaluateSequential(ReduceOps.java:248)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.count(ReferencePipeline.java:709)
        at org.projectnessie.gc.expire.PerContentDeleteExpired.identifyLiveFiles(PerContentDeleteExpired.java:136)
        at org.projectnessie.gc.expire.PerContentDeleteExpired.expire(PerContentDeleteExpired.java:73)
        at org.projectnessie.gc.expire.local.DefaultLocalExpire.expireSingleContent(DefaultLocalExpire.java:109)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.concurrent.ConcurrentHashMap$KeySpliterator.forEachRemaining(ConcurrentHashMap.java:3573)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:960)
        at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:934)
        at java.base/java.util.stream.AbstractTask.compute(AbstractTask.java:327)
        at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:667)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:927)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
        at java.base/java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:657)
        at org.projectnessie.gc.expire.local.DefaultLocalExpire.expireInForkJoinPool(DefaultLocalExpire.java:96)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1456)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
Caused by: java.lang.ClassNotFoundException: software.amazon.awssdk.services.kms.model.EncryptionAlgorithmSpec
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
        ... 46 more
```

There were [several related changes](https://github.com/projectnessie/nessie/releases/tag/nessie-0.105.1) in `0.105.1`, including adding `software.amazon.awssdk:kms` [as a dependency](https://github.com/projectnessie/nessie/pull/11300/files), but something seems to be incorrect.

### How to reproduce it

1. Run Nessie GC, with iceberg files in S3 compatible storage
2. e.g. `docker run --rm ghcr.io/projectnessie/nessie-gc:0.105.1 gc --uri https://my.host/api/v2/ --inmemory --iceberg s3.access-key-id=somekey --iceberg s3.secret-access-key=somekey --iceberg s3.endpoint=https://my.object.host/ --iceberg s3.path-style-access=true`
3. Receive `NoClassDefFoundError`

### Nessie server type (docker/uber-jar/built from source) and version

docker

### Client type (Ex: UI/Spark/pynessie ...) and version

Nessie GC versions `>=0.105.1`

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by dimas-b**
Fixes #11432
Relates to #11300

### CODE REVIEW

**Review by XN137 — APPROVED** [review]
change lgtm

makes me wonder though why the gc tool does not depend on `catalog/files/impl` (aka "Nessie - Catalog - Object I/O") module (where we made the change already)
